server:
  port: 80
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 90000
        connectTimeout: 90000
spring:
  application:
    name: tingshu-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.121.130:8848
    sentinel:
      transport:
        dashboard: 192.168.121.130:8080
    openfeign:
      lazy-attributes-resolution: true
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        #        - id: service-all1
        #          uri: lb://service-all
        #          predicates:
        #            - Path=/api/**
        #        - id: service-all2
        #          uri: lb://service-all
        #          predicates:
        #            - Path=/admin/**
        - id: tingshu-album
          uri: lb://tingshu-album
          predicates:
            - Path=/*/album/**
        - id: tingshu-user
          uri: lb://tingshu-user
          predicates:
            - Path=/*/user/**
        - id: tingshu-order
          uri: lb://tingshu-order
          predicates:
            - Path=/*/order/**
        - id: service-live
          uri: lb://service-live
          predicates:
            - Path=/*/live/**
        - id: service-live-websocket
          uri: lb:ws://service-live #ws://192.168.121.130:8507
          predicates:
            - Path=/api/websocket/**
        - id: tingshu-account
          uri: lb://tingshu-account
          predicates:
            - Path=/*/account/**
        - id: tingshu-comment
          uri: lb://tingshu-comment
          predicates:
            - Path=/*/comment/**
        - id: service-dispatch
          uri: lb://service-dispatch
          predicates:
            - Path=/*/dispatch/**
        - id: tingshu-payment
          uri: lb://tingshu-payment
          predicates:
            - Path=/*/payment/**
        - id: tingshu-system
          uri: lb://tingshu-system
          predicates:
            - Path=/*/system/**
        - id: tingshu-search
          uri: lb://tingshu-search
          predicates:
            - Path=/*/search/**