server:
  port: 8501
mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 90000
        connectTimeout: 90000
spring:
  application:
    name: tingshu-album
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.76.100:8848
    sentinel:
      transport:
        dashboard: 192.168.76.100:8080
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
    allow-circular-references: true
  data:
    redis:
      host: 192.168.76.100
      port: 6389
      database: 0
      timeout: 1800000
      jedis:
        pool:
          max-active: 20 #最大连接数
          max-wait: -1    #最大阻塞等待时间(负数表示没限制)
          max-idle: 5    #最大空闲
          min-idle: 0     #最小空闲
    mongodb:
      host: 192.168.76.100
      port: 27017
      database: admin #指定操作的数据库
      password: '123'
      username: root
  kafka:
    bootstrap-servers: 192.168.76.100:9092
    producer:
      retries: 3  #设置大于0的值，则客户端会将发送失败的记录重新发送
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: service-album
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.76.100:3316/tingshu_album?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB     #单个文件最大限制
      max-request-size: 200MB  #多个文件最大限制
minio:
  endpoint: http://192.168.76.100:9000
  access-key: enjoy6288
  secret-key: enjoy6288
  bucket-name: tingshu
vod:
  appId: 1307503602
  secretId: AKID54ua5NSWXwOoDQXVO4a3Y6c4MezEOPFw
  secretKey: kKwR0RmzzubDes490f8SdeWRHyTl3ED4
  region: ap-guangzhou
  procedure: SimpleAesEncryptPreset #任务流
  tempPath: D:\tingshu\temp_path
  playKey: wrTwwu8U3DRSRDgC8l7q  #播放加密key
#vod:
#  appId: 1252137686
#  secretId: AKIDoRq10jHcjYBas56xb1C9sRq8C2KOFuNn
#  secretKey: WfgYMyLYZQCznQpqMl096AxaCetvmYK7
#  region: ap-guangzhou
#  procedure: SimpleAesEncryptPreset #任务流
#  tempPath: D:\tingshu\temp_path
#  playKey: wrTwwu8U3DRSRDgC8l7q  #播放加密key
